app/build.gradle.kts
data/build.gradle.kts
domain/build.gradle.kts
gradle/libs.versions.toml

코틀린 버전 추가
> 실제 작업 내용
|:---|---|---|
> 리뷰어들에게 전할 말

[feature] 코틀린 버전 추가

---

core/coroutine/src/main/AndroidManifest.xml
core/designsystem/src/main/AndroidManifest.xml
core/designsystem/src/main/java/com/mashup/dorabangs/core/designsystem/component/card/CardProgressBar.kt
core/designsystem/src/main/java/com/mashup/dorabangs/core/designsystem/component/card/FeedCard.kt
core/designsystem/src/main/java/com/mashup/dorabangs/core/designsystem/component/card/FeedCardUiModel.kt
core/designsystem/src/main/java/com/mashup/dorabangs/core/designsystem/component/card/TextLoadingSkeleton.kt
core/designsystem/src/main/java/com/mashup/dorabangs/core/designsystem/component/chips/DoraChipUiModel.kt
core/designsystem/src/main/java/com/mashup/dorabangs/core/designsystem/component/chips/DoraChips.kt
core/designsystem/src/main/java/com/mashup/dorabangs/core/designsystem/component/topbar/DorabangsTopAppBar.kt
core/designsystem/src/main/java/com/mashup/dorabangs/core/designsystem/theme/Colors.kt
core/designsystem/src/main/java/com/mashup/dorabangs/core/designsystem/theme/DorabansTheme.kt
core/designsystem/src/main/java/com/mashup/dorabangs/core/designsystem/theme/Radius.kt
core/designsystem/src/main/res/drawable/ic_android_white_24dp.xml
core/designsystem/src/main/res/values/string.xml
core/designsystem/src/main/res/values/strings.xml
core/navigation/src/main/AndroidManifest.xml
data/src/main/AndroidManifest.xml
feature/home/src/main/AndroidManifest.xml
feature/home/src/main/java/com/mashup/dorabangs/feature/home/HomeContract.kt
feature/home/src/main/java/com/mashup/dorabangs/feature/home/HomeScreen.kt
feature/home/src/main/java/com/mashup/dorabangs/feature/home/HomeViewModel.kt

- 홈 화면 구현
> 실제 작업 내용
- 홈 화면 UI 구현
- 홈 화면 Tab 컴포넌트 구현
- 스켈레톤 Text UI 컴포넌트 구현
- Progress Bar 컴포넌트 구현
|요약중|Sticky|
|---|---|
|<img width="409" alt="image" src="https://github.com/mash-up-kr/Dorabangs_Android/assets/74997185/a29a7c9e-277b-43b3-8de1-e20ae6b7387c">|<img width="413" alt="image" src="https://github.com/mash-up-kr/Dorabangs_Android/assets/74997185/ee49a18d-4681-48c8-94a3-b9cff1398a8e">|
> 리뷰어들에게 전할 말
- 화이팅
close #29

홈 화면 UI 개발

---

app/src/main/java/com/mashup/dorabangs/navigation/MainNavHost.kt
data/src/main/kotlin/com/mashup/dorabangs/data/datasource/remote/api/FolderRemoteDataSource.kt
data/src/main/kotlin/com/mashup/dorabangs/data/datasource/remote/impl/FolderRemoteDataSourceImpl.kt
data/src/main/kotlin/com/mashup/dorabangs/data/di/DataSourceModule.kt
data/src/main/kotlin/com/mashup/dorabangs/data/di/NetworkModule.kt
data/src/main/kotlin/com/mashup/dorabangs/data/di/RepositoryModule.kt
data/src/main/kotlin/com/mashup/dorabangs/data/di/ServiceModule.kt
data/src/main/kotlin/com/mashup/dorabangs/data/model/DoraResponse.kt
data/src/main/kotlin/com/mashup/dorabangs/data/model/FolderResponseModel.kt
data/src/main/kotlin/com/mashup/dorabangs/data/network/service/FolderService.kt
data/src/main/kotlin/com/mashup/dorabangs/data/repository/FolderRepositoryImpl.kt
domain/src/main/kotlin/com/mashup/dorabangs/domain/model/Folder.kt
domain/src/main/kotlin/com/mashup/dorabangs/domain/repository/FolderRepository.kt
domain/src/main/kotlin/com/mashup/dorabangs/domain/usecase/folder/GetFolderById.kt
domain/src/main/kotlin/com/mashup/dorabangs/domain/usecase/folder/GetFolderList.kt

- 폴더 리스트 및 폴더 가져오기 네트워크 구현
> 실제 작업 내용
- 폴더 Get 관련 요청 네트워킹, Usecase 만듦
> 리뷰어들에게 전할 말
...
close #56

내 폴더 목록 조회 API 연결

---

.github/workflows/build.yaml
app/build.gradle.kts

> 실제 작업 내용
|:---|---|---|
> 리뷰어들에게 전할 말
close #

google-services 파일 CI 추가

---

.github/workflows/build.yaml
app/build.gradle.kts

> 실제 작업 내용
|:---|---|---|
> 리뷰어들에게 전할 말
close #

Google json ci

---

app/src/main/java/com/mashup/dorabangs/navigation/MainNavHost.kt
core/navigation/src/main/java/com/mashup/core/navigation/NavigationRoute.kt
feature/home/build.gradle.kts
feature/home/src/main/java/com/mashup/dorabangs/feature/createfolder/HomeCreateFolderScreen.kt
feature/home/src/main/java/com/mashup/dorabangs/feature/home/HomeContract.kt
feature/home/src/main/java/com/mashup/dorabangs/feature/home/HomeSideEffect.kt
feature/home/src/main/java/com/mashup/dorabangs/feature/home/HomeViewModel.kt
feature/home/src/main/java/com/mashup/dorabangs/feature/navigation/HomeCreateFolderNavigation.kt
feature/home/src/main/java/com/mashup/dorabangs/feature/navigation/HomeNavigation.kt
feature/save/src/main/java/com/dorabangs/feature/navigation/SaveLinkSelectFolderNavigation.kt
feature/save/src/main/java/com/dorabangs/feature/save/screen/DoraLinkSaveSelectFolderRoute.kt

저장 이후에 홈으로 이동;; 
> 실제 작업 내용
수정 내역이 꽤 잇네요 ㅠ;;
save 해주기 위해서 폴더 생성 이후에 save함.
BUT !!!!!! 아직 서버쪽에서 폴더 생성 이후에 생성된 ID리턴을 아직 안해줘서, 추후에 살짝 수정해야함 ! 
|:---|---|---|
> 리뷰어들에게 전할 말
close #

[feature] 홈으로 이동하는 로직 수정

---

feature/storage/src/main/java/com/mashup/dorabangs/feature/storage/storage/StorageFolderListItem.kt
feature/storage/src/main/java/com/mashup/dorabangs/feature/storage/storage/StorageScreen.kt
feature/storage/src/main/java/com/mashup/dorabangs/feature/storage/storagedetail/StorageDetailHeader.kt
feature/storage/src/main/java/com/mashup/dorabangs/feature/storage/storagedetail/StorageDetailList.kt
feature/storage/src/main/java/com/mashup/dorabangs/feature/storage/storagedetail/model/StorageDetailState.kt

> 실제 작업 내용
- 진짜 아이콘만 적용했어용
|:---|---|---|
> 리뷰어들에게 전할 말
close #

보관함 및 보관함 상세 아이콘 적용

---

app/src/main/java/com/mashup/dorabangs/navigation/MainNavHost.kt
data/src/main/kotlin/com/mashup/dorabangs/data/datasource/remote/api/FolderRemoteDataSource.kt
data/src/main/kotlin/com/mashup/dorabangs/data/datasource/remote/impl/FolderRemoteDataSourceImpl.kt
data/src/main/kotlin/com/mashup/dorabangs/data/model/CreateFolderResponseModel.kt
data/src/main/kotlin/com/mashup/dorabangs/data/network/service/FolderService.kt
data/src/main/kotlin/com/mashup/dorabangs/data/repository/FolderRepositoryImpl.kt
domain/src/main/kotlin/com/mashup/dorabangs/domain/model/DoraCreateFolderModel.kt
domain/src/main/kotlin/com/mashup/dorabangs/domain/repository/FolderRepository.kt
domain/src/main/kotlin/com/mashup/dorabangs/domain/usecase/folder/CreateFolderUseCase.kt
feature/home/src/main/java/com/mashup/dorabangs/feature/home/HomeContract.kt
feature/home/src/main/java/com/mashup/dorabangs/feature/home/HomeViewModel.kt
feature/save/src/main/java/com/dorabangs/feature/navigation/SaveLinkSelectFolderNavigation.kt
feature/save/src/main/java/com/dorabangs/feature/save/DoraSaveSideEffect.kt
feature/save/src/main/java/com/dorabangs/feature/save/DoraSaveViewModel.kt
feature/save/src/main/java/com/dorabangs/feature/save/screen/DoraLinkSaveSelectFolderRoute.kt
feature/storage/src/main/java/com/mashup/dorabangs/feature/folders/FolderManageViewModel.kt

url 저장하는거 서버쪽 수정 이어받아서 마무리 했습니다
> 실제 작업 내용
- 새로 추가한 폴더에 url 저장
- 기존 폴더에 url 저장
- 중복된 폴더명 가지고 있다가 수정시 반영
https://github.com/user-attachments/assets/d63d30d0-7aa2-4785-8c1a-42165b8ba5da
> 리뷰어들에게 전할 말
빠이팅~

[feature] url 저장 기능 마무리~

---

app/src/main/java/com/mashup/dorabangs/navigation/MainNavHost.kt
core/designsystem/src/main/java/com/mashup/dorabangs/core/designsystem/component/topbar/DorabangsTopAppBar.kt
core/navigation/src/main/java/com/mashup/core/navigation/NavigationRoute.kt
feature/home/build.gradle.kts
feature/home/src/main/java/com/mashup/dorabangs/feature/home/HomeRoute.kt
feature/home/src/main/java/com/mashup/dorabangs/feature/home/HomeScreen.kt
feature/home/src/main/java/com/mashup/dorabangs/feature/navigation/HomeNavigation.kt
feature/home/src/main/java/com/mashup/dorabangs/feature/navigation/HomeTutorialNavigation.kt
feature/home/src/main/java/com/mashup/dorabangs/feature/tutorial/HomeTutorialScreen.kt
feature/home/src/main/java/com/mashup/dorabangs/feature/tutorial/TutorialVideo.kt
feature/home/src/main/res/values/string.xml
gradle/libs.versions.toml

- 홈 튜토리얼 영상 ExoPlayer
> 실제 작업 내용
- 홈캐러셀에서 "링크 저장하는 방법이에요" 누르면 넘어가는 튜토리얼 화면 만들었습니다.
- 시스템 모달 좀더 알아봐야할 것 같아요,,더보기 가능한게 뭔지 찾아봐야할듯!
https://github.com/user-attachments/assets/f35a3288-5ba7-4eb2-961e-be6f9fda6429
> 리뷰어들에게 전할 말
영케이 얼굴 보면서 도라방스 화이팅!
close #95

홈 튜토리얼 영상 ExoPlayer

---

core/designsystem/src/main/java/com/mashup/dorabangs/core/designsystem/component/toast/DorabangsToast.kt

토스트 만듦
> 실제 작업 내용
스낵바로 토스트 만듦..
토스트 style을 통해 2가지 이미지를 분기 쳐야함
> 리뷰어들에게 전할 말
굿~

[feature] 토스트 만듦

---

data/src/main/kotlin/com/mashup/dorabangs/data/datasource/remote/api/AIClassificationRemoteDataSource.kt
data/src/main/kotlin/com/mashup/dorabangs/data/datasource/remote/impl/AIClassificationRemoteDataSourceImpl.kt
data/src/main/kotlin/com/mashup/dorabangs/data/model/AiClassificationMoveSinglePostRequestModel.kt
data/src/main/kotlin/com/mashup/dorabangs/data/model/AiClassificationMoveSinglePostResponseModel.kt
data/src/main/kotlin/com/mashup/dorabangs/data/network/service/AIClassificationService.kt
feature/classification/src/main/java/com/mashup/feature/classification/ClassificationCompleteScreen.kt
feature/classification/src/main/java/com/mashup/feature/classification/ClassificationScreen.kt
feature/classification/src/main/java/com/mashup/feature/classification/ClassificationState.kt
feature/classification/src/main/java/com/mashup/feature/classification/ClassificationViewModel.kt
feature/classification/src/main/res/values/string.xml

chips 추가
하는김에 클릭 index 수정도 추가
> 실제 작업 내용
영상으로 보시오
https://github.com/user-attachments/assets/1227f2b1-caa9-4609-9b17-f228b62102ff
> 리뷰어들에게 전할 말
도라방스 화이팅!

[feature] chips 추가

---

core/designsystem/src/main/java/com/mashup/dorabangs/core/designsystem/component/card/FeedCard.kt
core/designsystem/src/main/java/com/mashup/dorabangs/core/designsystem/component/card/FeedCardUiModel.kt
core/designsystem/src/main/java/com/mashup/dorabangs/core/designsystem/component/chips/DoraChipUiModel.kt
data/src/main/kotlin/com/mashup/dorabangs/data/datasource/remote/api/AIClassificationRemoteDataSource.kt
data/src/main/kotlin/com/mashup/dorabangs/data/datasource/remote/api/FolderRemoteDataSource.kt
data/src/main/kotlin/com/mashup/dorabangs/data/datasource/remote/impl/AIClassificationRemoteDataSourceImpl.kt
data/src/main/kotlin/com/mashup/dorabangs/data/datasource/remote/impl/FolderRemoteDataSourceImpl.kt
data/src/main/kotlin/com/mashup/dorabangs/data/model/classification/AIClassificationAIPostListResponseModel.kt
data/src/main/kotlin/com/mashup/dorabangs/data/network/service/AIClassificationService.kt
data/src/main/kotlin/com/mashup/dorabangs/data/network/service/FolderService.kt
data/src/main/kotlin/com/mashup/dorabangs/data/repository/AIClassificationRepositoryImpl.kt
data/src/main/kotlin/com/mashup/dorabangs/data/repository/FolderRepositoryImpl.kt
domain/src/main/kotlin/com/mashup/dorabangs/domain/model/AIClassificationFolders.kt
domain/src/main/kotlin/com/mashup/dorabangs/domain/model/classification/AIClassificationFeedPost.kt
domain/src/main/kotlin/com/mashup/dorabangs/domain/repository/AIClassificationRepository.kt
domain/src/main/kotlin/com/mashup/dorabangs/domain/repository/FolderRepository.kt
domain/src/main/kotlin/com/mashup/dorabangs/domain/usecase/aiclassification/GetAIClassificationPostsUseCase.kt
domain/src/main/kotlin/com/mashup/dorabangs/domain/usecase/folder/GetSavedLinksFromFolderUseCase.kt
feature/classification/build.gradle.kts
feature/classification/src/main/java/com/mashup/feature/classification/ClassificationListScreen.kt
feature/classification/src/main/java/com/mashup/feature/classification/ClassificationScreen.kt
feature/classification/src/main/java/com/mashup/feature/classification/ClassificationState.kt
feature/classification/src/main/java/com/mashup/feature/classification/ClassificationViewModel.kt
feature/home/src/main/java/com/mashup/dorabangs/feature/home/HomeScreen.kt
feature/home/src/main/java/com/mashup/dorabangs/feature/home/HomeViewModel.kt
feature/storage/src/main/java/com/mashup/dorabangs/feature/storage/storagedetail/StorageDetailList.kt
feature/storage/src/main/java/com/mashup/dorabangs/feature/storage/storagedetail/StorageDetailViewModel.kt
feature/storage/src/main/java/com/mashup/dorabangs/feature/storage/storagedetail/model/PostCardMapper.kt

페이징 적용했습니다
아직 추가할 게 더 있지만, 일단 올립니당
서버에서 나중에 저장할 목록이 내려오지 않아서;;; 서버쪽에서 봐줘야함미다
아직 이동 + 삭제 버튼 은 구현 안했습니다
스크롤 맨위로만 작동합니다 아직 적절한 구현 생각중 ,,
안만들어놨던 키워드 스크롤 추가했음미다
여기도 북마크가 있네 
더보기도 있네;;
> 실제 작업 내용
페이징 적용
https://github.com/user-attachments/assets/2d87cb23-9711-4cf1-8f23-3d2a939df7a2
https://github.com/user-attachments/assets/9687d08f-cd76-4a02-a2dd-8f457ff55b58
> 리뷰어들에게 전할 말
화이팅
close #

[feature] paging 적용

---

core/designsystem/src/main/java/com/mashup/dorabangs/core/designsystem/component/card/FeedCard.kt
feature/classification/src/main/java/com/mashup/feature/classification/ClassificationListScreen.kt
feature/home/src/main/java/com/mashup/dorabangs/feature/home/HomeScreen.kt
feature/storage/src/main/java/com/mashup/dorabangs/feature/storage/storagedetail/StorageDetailList.kt

분기추가로 북마크, 더보기 보여줄지 말지 결정
이놈 왜자꾸 pr 올려? 라고 생각하실 수 있지만, 다음 작업이 delete 와 같은 API 작업이라 diff가 많을 예정이라;
미리 올렸슴다
> 실제 작업 내용
> 리뷰어들에게 전할 말
close #

[feature] feedcard 분기 추가

---

data/src/main/kotlin/com/mashup/dorabangs/data/di/NetworkModule.kt

재변경
네뜨워크 인터셉터에 넣으래용 플리퍼가 
빼니까 토큰 인터셉터를 못하네 
> 실제 작업 내용
|:---|---|---|
> 리뷰어들에게 전할 말
close #

[refactoring] 재변경

---

core/designsystem/src/main/java/com/mashup/dorabangs/core/designsystem/component/buttons/ButtonType.kt
core/designsystem/src/main/java/com/mashup/dorabangs/core/designsystem/component/buttons/GradientButton.kt
core/designsystem/src/main/java/com/mashup/dorabangs/core/designsystem/theme/Colors.kt
feature/classification/src/main/java/com/mashup/feature/classification/ClassificationListScreen.kt
feature/home/src/main/java/com/mashup/dorabangs/feature/home/HomeScreen.kt

- AI 분류 디자인 적용했습니다.
> 실제 작업 내용
- 가운데 카테고리 모두이동이랑 옮기기 버튼 적용!
> 리뷰어들에게 전할 말
- 지피티 미워ㅜ 마라엽떡 먹고싶다.
close #120

AI분류 디자인 적용 레츠고

---

core/designsystem/src/main/java/com/mashup/dorabangs/core/designsystem/component/chips/FeedUiModel.kt
feature/classification/src/main/java/com/mashup/feature/classification/ClassificationListScreen.kt
feature/classification/src/main/java/com/mashup/feature/classification/ClassificationScreen.kt
feature/classification/src/main/java/com/mashup/feature/classification/ClassificationState.kt
feature/classification/src/main/java/com/mashup/feature/classification/ClassificationViewModel.kt

스크롤 필터 추가함
실제 페이징 데이터를 수정하면 안돼서 (생각해보면 당연한,,, 짜르고 나서 다시.전체누르면 자른 데이터가 날라가있잖아 )
뷰쪽에서 걸러줬습니다
> 실제 작업 내용
상동
https://github.com/user-attachments/assets/54ac2e6e-d81d-4a64-a1e6-451ab0ba1168
> 리뷰어들에게 전할 말

[feature] 스크롤 + 필터 추가

---

app/src/main/java/com/mashup/dorabangs/DoraOverlayService.kt
data/src/main/kotlin/com/mashup/dorabangs/data/datasource/remote/api/AIClassificationRemoteDataSource.kt
data/src/main/kotlin/com/mashup/dorabangs/data/network/service/AIClassificationService.kt

외부에서 여러개 막 공유하기하면 안사라지는거 수정
전체 이동시에 응답이 달라서 수정안되던 것 까지 같이 수정
> 실제 작업 내용
서비스쪽 수정
전체 이동시에 응답이 달라서 수정안되던 것 까지 같이 수정
> 리뷰어들에게 전할 말
이슈 #111 수정~
close #111

[fix] 여러개 마~~~악 누르면 안사라지는 버그 수정

---

app/src/main/java/com/mashup/dorabangs/DoraShareActivity.kt

크래시 대응
> 실제 작업 내용
입니다
https://github.com/user-attachments/assets/115b78d1-d276-43cd-91f4-034f5ea62de3

[fix] 크래시 대응

---

core/webview/build.gradle.kts
core/webview/src/main/java/com/mashup/dorabangs/core/webview/DoraWebView.kt
gradle/libs.versions.toml

#	gradle/libs.versions.toml
> 실제 작업 내용
|:---|---|---|
> 리뷰어들에게 전할 말
close #

웹뷰 유튜브 영상 안보이는 이슈 체리픽

---

app/src/main/java/com/mashup/dorabangs/navigation/MainNavHost.kt

링크 저장 목록에서 폴더 생성시에
홈으로 나가던 것, 뒤로 가는 것으로 수정

[feature] 뒤로가기시에 홈으로 가던 . 것수정

---

core/designsystem/src/main/java/com/mashup/dorabangs/core/designsystem/component/folder/DoraSelectableFolderListItems.kt
feature/save/src/main/java/com/dorabangs/feature/save/DoraSaveState.kt
feature/save/src/main/java/com/dorabangs/feature/save/DoraSaveViewModel.kt
feature/save/src/main/java/com/dorabangs/feature/save/screen/DoraLinkSaveSelectFolderScreen.kt

[feature] save 쪽에 로딩 추가

---

.github/workflows/build.yaml

수동빌드 추가
> 실제 작업 내용
|:---|---|---|
> 리뷰어들에게 전할 말
close #

[feature] 수동빌드 추가

---

.github/workflows/create_artifact.yaml

마스터에서 피알 생성하면 다운로드 아티팩트 생성
https://github.com/mash-up-kr/Dorabangs_Android/pull/163 <- 요기 맨밑에 보면됨
> 실제 작업 내용
상동
> 리뷰어들에게 전할 말
이제부터 마스터로 머지 == 배포 로 !

[feature] artifact upload 추가

---

data/build.gradle.kts
data/src/test/kotlin/com/mashup/dorabangs/data/AIClassificationRepositoryImplTest.kt

레포지토리 테스트 추가
> 실제 작업 내용
|:---|---|---|
> 리뷰어들에게 전할 말
close #

[feature] repository 테스트 추가

---

.github/workflows/auto-tagging.yaml

마스터 머지시에 오토 태깅 해주는 것 추가해봤습니당
사용법 : 마스터 머지시에, 붙여논 라벨 (major, minor, patch)에 따라 한개씩 올려줌
* 1.0.0 -> major 라벨 붙임 -> 2.0.0
* 2.0.1 -> minor, patch 라벨 붙임 -> 2.1.2
> 실제 작업 내용
마스터 머지시에 오토 태깅
> 리뷰어들에게 전할 말
주의사항 = 1.0.0 없으면 만드는건 안해서,,, 1.0.0은 미리 만들고 이후부터 적용이 가능할듯,,

[feature] 오토 태깅 추가

---

.github/workflows/build.yaml
.github/workflows/common-setup.yaml
.github/workflows/create_artifact.yaml
.github/workflows/lint_check.yaml
README.md
core/designsystem/src/main/java/com/mashup/dorabangs/core/designsystem/component/bottomsheet/BottomSheetType.kt

readme update
bug 수정 (secrets의 google-service.json이 안들어가는 버그 ? 가있어서 세팅 다시해줌 + 로직 살짝 수정 )

readme update, 버그 수정

---

gradle/libs.versions.toml

> 실제 작업 내용
|:---|---|---|
> 리뷰어들에게 전할 말
close #

[feature] 버전업 1.0.1

---

gradle/libs.versions.toml

version_code 10
> 실제 작업 내용
|:---|---|---|
> 리뷰어들에게 전할 말
close #

[feature] version_code = 10

---

gradle/libs.versions.toml

v1.0.1, versioncode 10

---

.github/workflows/create_artifact.yaml
app/build.gradle.kts

ㅋㅋ ci에서 사이닝키가 중복돼서 없애버렸는데, 저거 없음 로컬에서 릴리즈 빌드가 안되네용
ci란 값을 보고 있으면 쓰고, 없으면 안쓰고~
> 실제 작업 내용
상동 (염색체)

[fix] signing key 추가

---

.github/workflows/create_artifact.yaml

커밋 개수를 못가져오는 것 같아서 history 가져 와봤어요

[feature] artifcat 생성시에 history 다 가져오기

---

.github/workflows/auto-tagging.yaml

as-is = 마스터 머지 되고 난 이후 
to-be = 마스터 머지 되고 난 이후 + 라벨이 한개라도 붙어있는 경우 
수행 되게함
> 실제 작업 내용
상동

[feature] auto-tagging 로직 수정

---

.github/workflows/create_artifact_and_deployment.yaml
gradle/libs.versions.toml

cd 추가 테스트~ (성공~)
master 머지 시에 스토어에 자동 배포됩니당
버전도 수정하는 거 없이 자동으로 메이저 마이너 올렸음 하는데,, 좋은 방법 없나...
[ 사용 방법 ]
1. 마스터 머지 전에 pr 을 통해 배포하고 싶은 versionName을 명시한다 (회사처럼 배포 주기가 없기 때문에 알아서 올려야함;;)
2. 머지 pr에 버전을 올리고 싶은 라벨을 달아주면(위의 versionName과 같이 쓰게끔 세팅해주면)
오토 태깅 + 자동 배포가 가능 
[ 예시 ]
현재 versionName이 1.0.3 일 때,
1. versionName을 1.0.4로 수정하고 pr을 만듦
2. pr에 라벨로 patch를 붙임
=> master로 머지되면, v1.0.4로 자동 배포 및 태그 따줌
**쉽죠**
> 실제 작업 내용
자 동 배 포
> 리뷰어들에게 전할 말
저 잘 했 죠

[feature] cd 추가

---

core/designsystem/src/main/java/com/mashup/dorabangs/core/designsystem/component/snackbar/DoraCloseButton.kt
core/designsystem/src/main/java/com/mashup/dorabangs/core/designsystem/component/snackbar/doraiconclosev2/IcCloseButton.kt
feature/classification/src/main/java/com/mashup/feature/classification/ClassificationListScreen.kt

디자인 수정입미다
> 실제 작업 내용
디자인 수정입니다
https://www.figma.com/design/kJMdgWGctjSMRuQqqMQlOs/Linkit--(v2)?node-id=8529-26851&node-type=FRAME&t=EQZlUHJkrFC6QfxK-0

[디자인] ai classification 디자인 수정

---

app/build.gradle.kts
buildSrc/src/main/kotlin/GitUtil.kt

하동
> 실제 작업 내용
그냥 확장함수로 만들었습니다 깔끔해서 ,,

[refactoring] project 확장함수로 변경

---

.github/workflows/build.yaml
.github/workflows/create_artifact_and_deployment.yaml
.github/workflows/lint_check.yaml
app/build.gradle.kts
core/coroutine/build.gradle.kts
core/designsystem/build.gradle.kts
core/navigation/build.gradle.kts
core/webview/build.gradle.kts
data/build.gradle.kts
domain/build.gradle.kts
feature/classification/build.gradle.kts
feature/home/build.gradle.kts
feature/onboarding/build.gradle.kts
feature/save/build.gradle.kts
feature/share/build.gradle.kts
feature/storage/build.gradle.kts

자바 버전 17로 내렸어요
> 실제 작업 내용
자바 버전 17로 내렸어요
> 리뷰어들에게 전할 말
1. 자바 17 is LTS (29년까지래요;;)
2. 최신버전 아닌 살짝 아랫버전의 안전한 LTS
3. 외에 짜잘한 https://blog.naver.com/seek316/223330639473 추가 기능들ㅇ ㅣ있지만, ,와닿진 않네용
4. 굳이 억지부리자면 """ """로 가독성있게 읽기 가능 ㅋ ㅋ;;?

[refactoring] java version 17 gogo

---

gradle/libs.versions.toml

> 실제 작업 내용
|:---|---|---|
> 리뷰어들에게 전할 말
close #

test v1.0.4

---

.github/workflows/common-setup.yaml
.github/workflows/create_artifact_and_deployment.yaml
gradle/libs.versions.toml

런타임 익셉션 수정 위한 수정
> 실제 작업 내용
secret값 수정

[feature] version up + base url 수정

---

.github/workflows/create_artifact_and_deployment.yaml

배포 안하고 내부테스트 로
> 실제 작업 내용
|:---|---|---|
> 리뷰어들에게 전할 말
close #

test용 1.0.5

---

core/designsystem/src/main/java/com/mashup/dorabangs/core/designsystem/component/snackbar/DorabangsSnackBar.kt
core/designsystem/src/main/java/com/mashup/dorabangs/core/designsystem/component/toast/DorabangsToast.kt
core/designsystem/src/main/java/com/mashup/dorabangs/core/designsystem/theme/Colors.kt

- Toast 디자인 수정 반영
> 실제 작업 내용
Toast 디자인 수정
|스낵바|토스트|
|---|---|
|<img width="408" alt="image" src="https://github.com/user-attachments/assets/936a3d5a-307b-42df-ae84-c7c29c932da6">|<img width="372" alt="image" src="https://github.com/user-attachments/assets/0d33ba2f-ef56-4fca-bbdd-156aac9386a3">|
> 리뷰어들에게 전할 말
close #

Toast 디자인 수정 반영

---

core/designsystem/src/main/java/com/mashup/dorabangs/core/designsystem/theme/Colors.kt
feature/save/src/main/java/com/dorabangs/feature/save/screen/DoraLinkSaveTitleAndLinkScreen.kt

> 실제 작업 내용
|링크썸네일|
|---|
|<img width="423" alt="image" src="https://github.com/user-attachments/assets/47c97463-8d95-4aa8-abf7-2416d912f04e">|
> 리뷰어들에게 전할 말
close #

링크 썸네일 디자인 수정 반영

---

core/designsystem/src/main/java/com/mashup/dorabangs/core/designsystem/component/topbar/TopAppBarType.kt
core/designsystem/src/main/res/drawable/ic_fab_add.xml
feature/home/src/main/java/com/mashup/dorabangs/feature/home/HomeScreen.kt

- FAB 생성
> 실제 작업 내용
|FAB 버튼|
|---|
|<img width="416" alt="image" src="https://github.com/user-attachments/assets/0021f3a5-e568-4b00-a54e-95cb42f3f125">|
> 리뷰어들에게 전할 말
close #

디자인 변경: FAB 생성

---

app/build.gradle.kts
build.gradle.kts
gradle/libs.versions.toml

어 떤 데 ?
> 실제 작업 내용
> 리뷰어들에게 전할 말
도라방스 여전히 화이팅!

[feature] crashlytics를 추가해 보았읍니다

---

gradle/libs.versions.toml

파베 포함한 1.0.7 on
> 실제 작업 내용
버전 - 업

[chore] 버전 업

---

.github/workflows/auto-assignee.yaml

auto_assignees 추가
> 실제 작업 내용
pr 만들 때 그냥 Assignees 도 추가하지 마! 
다 하지마 ! 다 때려쳐 !!!!!
자동으로 넣어줍니다 ~

[feature] auto_assignees 추가
